name: landa
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  crypto: ^3.0.6
  path: ^1.9.1
  path_provider: ^2.1.5
  file_picker: ^10.3.2
  open_filex: ^4.7.0
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  image: ^4.5.4
  video_thumbnail: ^0.5.6
  video_player: ^2.10.0
  syncfusion_flutter_pdfviewer: ^30.1.40

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/tray/landa_tray.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/tray/landa_tray.png
  min_sdk_android: 21
  remove_alpha_ios: true
