version: 1

script:
  - rm -rf AppDir
  - mkdir -p AppDir
  - cp -r build/linux/x64/release/bundle/* AppDir/
  - mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
  - cp assets/tray/landa_tray.png AppDir/usr/share/icons/hicolor/256x256/apps/landa.png
  - install -Dm644 .github/appimage/landa.desktop AppDir/usr/share/applications/landa.desktop

AppDir:
  path: ./AppDir
  app_info:
    id: com.example.landa
    name: Landa
    icon: landa
    version: !ENV '${APP_VERSION}'
    exec: landa-bin
    exec_args: $@
  apt:
    arch: amd64
    allow_unauthenticated: true
    sources:
      - sourceline: deb https://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
        key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x871920D1991BC93C
      - sourceline: deb https://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
        key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x871920D1991BC93C
      - sourceline: deb https://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
        key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x871920D1991BC93C
    include:
      - libgtk-3-0
      - libayatana-appindicator3-1
      # Ubuntu 22.04/jammy ships the mpv runtime as libmpv1.
      - libmpv1
      - libmediainfo0v5
      - libzen0v5
      - liblzma5

AppImage:
  arch: x86_64
  file_name: !ENV 'landa-v${APP_VERSION}-linux-x86_64.AppImage'
